### PR TITLE
Fix navigation direction and duplicate arrow

### LINKED ISSUE #134: Language bar direction is reversed, causing it to be the wrong way
- Priority-4 (Low e.g. Content is not perfectly aligned)

**Describe the bug**
The language bar takes a direction prop which sets the direction depending on the language direction. The current solution for changing the direction on the site reverses everything in the dom, causing the language bar to flip back to the incorrect direction.

image

**Team - do not edit**
@thejoefriel

### PR DESCRIPTION
**Pull request by cemalokten**
#### Issues this PR relates to #134 

closes #134

### CODE REVIEW

File: client/src/context/common.js [hunk 1]
```diff
@@ -31,22 +30,6 @@ const CommonLogic = ({ children }) => {
...
-  });
-
-  useEffect(() => {
-    setDirection(dir);
-    return () => {
-      setDirection('ltr');
-    };
-    // eslint-disable-next-line react-hooks/exhaustive-deps
-  }, [lng]);
-
```
Comment (RamyAlshurafa) [inline client/src/context/common.js:49]: why are you deleting this?!!

this is the code that changes the direction of the layout

**Review by RamyAlshurafa — CHANGES_REQUESTED** [review]

File: client/src/context/common.js (hunk 1 above)
Comment (cemalokten) [reply client/src/context/common.js:49]: Because it changes the direction of the entire site, the navigation bar requires a different layout for RTL, this method means that it doesn't meet the requirements of the design. The code that I have pushed works the same, but does not effect the nav-bar.

**Review by RamyAlshurafa — APPROVED** [review]
